services:
  intex-api:
    image: python:3.11-slim  # 
    container_name: intex-api
    ports:
      - "5446:8080"
    working_dir: /app
    command: bash -c "pip install -r requirements.txt && apt-get update && apt-get install -y supervisor && supervisord -c /app/supervisord.conf"
    volumes:
      - .:/app  # Map the local repository (where docker-compose.yml is located) to /app in the container
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PYTHONUNBUFFERED=1
    networks:
      - intex_network
networks:
  intex_network:
    external: true