[supervisord]
nodaemon=true

[program:gunicorn]
command = watchmedo auto-restart --directory=/app --pattern=*.py -- gunicorn -b 0.0.0.0:8080 app:app --reload
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn.err.log
stdout_logfile=/var/log/gunicorn.out.log
